=begin
#Syncro

#Welcome to the official Syncro API Docs.  To use these docs, you will need an active Syncro account. You can sign up for one here: [Syncro](https://syncromsp.com)  If you already have an active account, fill in your subdomain below and then click \"Authorize\" and fill in your api-key. The key is specific to your user account so it is found on the your user profile page.  Please review the [API License Agreement](https://syncromsp.com/syncromsp-api-license-agreement/) before using our API. By accessing our API, you are agreeing to the API License Agreement.  Please note there is a rate limit of 180 requests per minute per IP address on API Usage.    

OpenAPI spec version: v1
Contact: help@syncromsp.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.25
=end

require 'spec_helper'
require 'json'

# Unit tests for WmSyncromspSwaggerClient::AppointmentApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AppointmentApi' do
  before do
    # run before each test
    @instance = WmSyncromspSwaggerClient::AppointmentApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AppointmentApi' do
    it 'should create an instance of AppointmentApi' do
      expect(@instance).to be_instance_of(WmSyncromspSwaggerClient::AppointmentApi)
    end
  end

  # unit tests for appointments_get
  # Returns a paginated list of Appointments
  # Required permission: Appointments - View All (see-own never restricted) 
  # @param [Hash] opts the optional parameters
  # @option opts [Date] :date_from Returns Appointments that start after the date. Example \&quot;2019-01-25\&quot;
  # @option opts [Date] :date_to Returns Appointments that start before the date. Example \&quot;2019-12-31\&quot;
  # @option opts [BOOLEAN] :mine Return only current user&#x27;s appointments
  # @option opts [Integer] :page Returns provided page of results, each &#x27;page&#x27; contains 25 results
  # @return [nil]
  describe 'appointments_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for appointments_id_delete
  # Deletes an Appointment by ID
  # No special permissions required. 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'appointments_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for appointments_id_get
  # Retrieves an Appointment by ID
  # No special permissions required. 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse200]
  describe 'appointments_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for appointments_id_put
  # Updates an existing Appointment by ID
  # No special permissions required. 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [Body3] :body Appointment object that needs to be added
  # @return [nil]
  describe 'appointments_id_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for appointments_post
  # Creates an Appointment
  # No special permissions required. 
  # @param [Hash] opts the optional parameters
  # @option opts [Body2] :body Appointment object that needs to be added
  # @return [nil]
  describe 'appointments_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
