=begin
#Syncro

#Welcome to the official Syncro API Docs.  To use these docs, you will need an active Syncro account. You can sign up for one here: [Syncro](https://syncromsp.com)  If you already have an active account, fill in your subdomain below and then click \"Authorize\" and fill in your api-key. The key is specific to your user account so it is found on the your user profile page.  Please review the [API License Agreement](https://syncromsp.com/syncromsp-api-license-agreement/) before using our API. By accessing our API, you are agreeing to the API License Agreement.  Please note there is a rate limit of 180 requests per minute per IP address on API Usage.    

OpenAPI spec version: v1
Contact: help@syncromsp.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.25
=end

require 'spec_helper'
require 'json'

# Unit tests for WmSyncromspSwaggerClient::ContactApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ContactApi' do
  before do
    # run before each test
    @instance = WmSyncromspSwaggerClient::ContactApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ContactApi' do
    it 'should create an instance of ContactApi' do
      expect(@instance).to be_instance_of(WmSyncromspSwaggerClient::ContactApi)
    end
  end

  # unit tests for contacts_get
  # Returns a paginated list of Contacts
  # Required permission: Customers - View Detail Single-Customer Users can only access own contacts. 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :customer_id Any contacts attached to a Customer ID
  # @option opts [Integer] :page Returns provided page of results, each &#x27;page&#x27; contains 25 results
  # @return [nil]
  describe 'contacts_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for contacts_id_delete
  # Deletes a Contact
  # Required permission: Customers - Edit Single-Customer Users can only access own contacts. 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'contacts_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for contacts_id_get
  # Retrieves a Contact by ID
  # Required permission: Customers - View Detail Single-Customer Users can only access own contacts. 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2001]
  describe 'contacts_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for contacts_id_put
  # Updates an existing Contact
  # Required permission: Customers - Edit Single-Customer Users can only access own contacts. 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [Body7] :body Contact object that needs to be updated
  # @return [nil]
  describe 'contacts_id_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for contacts_post
  # Creates a Contact
  # Required permission: Customers - Edit Single-Customer Users can only access own contacts. 
  # @param [Hash] opts the optional parameters
  # @option opts [Body6] :body Contact object that needs to be added
  # @return [nil]
  describe 'contacts_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
