=begin
#Syncro

#Welcome to the official Syncro API Docs.  To use these docs, you will need an active Syncro account. You can sign up for one here: [Syncro](https://syncromsp.com)  If you already have an active account, fill in your subdomain below and then click \"Authorize\" and fill in your api-key. The key is specific to your user account so it is found on the your user profile page.  Please review the [API License Agreement](https://syncromsp.com/syncromsp-api-license-agreement/) before using our API. By accessing our API, you are agreeing to the API License Agreement.  Please note there is a rate limit of 180 requests per minute per IP address on API Usage.    

OpenAPI spec version: v1
Contact: help@syncromsp.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.25
=end

require 'spec_helper'
require 'json'

# Unit tests for WmSyncromspSwaggerClient::CustomerApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CustomerApi' do
  before do
    # run before each test
    @instance = WmSyncromspSwaggerClient::CustomerApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CustomerApi' do
    it 'should create an instance of CustomerApi' do
      expect(@instance).to be_instance_of(WmSyncromspSwaggerClient::CustomerApi)
    end
  end

  # unit tests for customers_autocomplete_get
  # Returns a paginated list of customers for autocomplete query
  # @param [Hash] opts the optional parameters
  # @option opts [String] :query Search query
  # @return [nil]
  describe 'customers_autocomplete_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for customers_get
  # Returns a paginated list of customers
  # Required permission: Customers - List/Search Single-Customer Users can only access own customer (self). 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :sort A customer field to order by. Examples \&quot;firstname ASC\&quot;, \&quot;city DESC\&quot;.
  # @option opts [String] :query Search query
  # @option opts [String] :firstname Any customers with a first name like the parameter
  # @option opts [String] :lastname Any customers with a last name like the parameter
  # @option opts [String] :business_name Any customers with a business name like the parameter
  # @option opts [Array<Integer>] :id Any customers with ID included in the list
  # @option opts [Array<Integer>] :not_id Any customers with ID not included in the list
  # @option opts [String] :email 
  # @option opts [String] :include_disabled Whether or not the returned list of customers includes disabled customers
  # @option opts [Integer] :page Returns provided page of results, each &#x27;page&#x27; contains 25 results
  # @return [nil]
  describe 'customers_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for customers_id_delete
  # Deletes a Customer by ID
  # Required permission: Customers - Delete 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'customers_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for customers_id_get
  # Retrieves a Customer by ID
  # Required permission: Customers - View Detail Single-Customer Users can only access own customer (self). 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'customers_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for customers_id_put
  # Updates an existing Customer by ID
  # Required permission: Customers - Edit Single-Customer Users can only access own customer (self). 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [Object] :body 
  # @return [nil]
  describe 'customers_id_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for customers_latest_get
  # Returns latest Customer
  # Required permission: Customers - Edit Single-Customer Users can only access own customer (self). 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'customers_latest_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for customers_post
  # Creates a Customer
  # Required permission: Customers - Create 
  # @param [Hash] opts the optional parameters
  # @option opts [Object] :body 
  # @return [nil]
  describe 'customers_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
