=begin
#Syncro

#Welcome to the official Syncro API Docs.  To use these docs, you will need an active Syncro account. You can sign up for one here: [Syncro](https://syncromsp.com)  If you already have an active account, fill in your subdomain below and then click \"Authorize\" and fill in your api-key. The key is specific to your user account so it is found on the your user profile page.  Please review the [API License Agreement](https://syncromsp.com/syncromsp-api-license-agreement/) before using our API. By accessing our API, you are agreeing to the API License Agreement.  Please note there is a rate limit of 180 requests per minute per IP address on API Usage.    

OpenAPI spec version: v1
Contact: help@syncromsp.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.25
=end

require 'spec_helper'
require 'json'

# Unit tests for WmSyncromspSwaggerClient::EstimateApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'EstimateApi' do
  before do
    # run before each test
    @instance = WmSyncromspSwaggerClient::EstimateApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of EstimateApi' do
    it 'should create an instance of EstimateApi' do
      expect(@instance).to be_instance_of(WmSyncromspSwaggerClient::EstimateApi)
    end
  end

  # unit tests for estimates_get
  # Returns a paginated list of Estimates
  # Required permission: Estimates - List/Search 
  # @param [Hash] opts the optional parameters
  # @option opts [BOOLEAN] :mine Returns estimates that belong to the current user
  # @option opts [String] :status Returns estimates with a given status. Possible values are &#x27;approved&#x27; and &#x27;declined&#x27;.
  # @option opts [Integer] :page Returns provided page of results, each &#x27;page&#x27; contains 50 results
  # @return [nil]
  describe 'estimates_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for estimates_id_convert_to_invoice_post
  # Convert an Estimate to an Invoice
  # Required permissions: \&quot;Estimates - View Details\&quot; and \&quot;Invoices - Create\&quot; 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'estimates_id_convert_to_invoice_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for estimates_id_delete
  # Deletes an Estimate by ID
  # Required permission: Estimates - Delete 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'estimates_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for estimates_id_email_post
  # Sends an Estimate to a Customer
  # Required permission: Estimates - View Details 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'estimates_id_email_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for estimates_id_get
  # Retrieves an Estimate by ID or number
  # Required permission: Estimates - View Details 
  # @param id Estimate ID
  # @param [Hash] opts the optional parameters
  # @option opts [String] :number Estimate number is used when the server cannot find an Estimate by ID
  # @return [nil]
  describe 'estimates_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for estimates_id_line_items_line_item_id_delete
  # Deletes a Line Item
  # Required permission: Estimates - Edit 
  # @param id 
  # @param line_item_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'estimates_id_line_items_line_item_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for estimates_id_line_items_line_item_id_put
  # Updates a Line Item
  # Required permission: Estimates - Edit 
  # @param id 
  # @param line_item_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Object] :body 
  # @return [nil]
  describe 'estimates_id_line_items_line_item_id_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for estimates_id_line_items_post
  # Adds a Line Item to an Estimate
  # Required permission: Estimates - Edit 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [Object] :body 
  # @return [nil]
  describe 'estimates_id_line_items_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for estimates_id_print_post
  # Queues a print job for an Estimate
  # Required permission: Estimates - View Details 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'estimates_id_print_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for estimates_id_put
  # Updates an existing Estimate by ID
  # Required permission: Estimates - Edit 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [Body11] :body 
  # @return [nil]
  describe 'estimates_id_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for estimates_post
  # Creates an Estimate
  # Required permission: Estimates - Create 
  # @param [Hash] opts the optional parameters
  # @option opts [Body10] :body 
  # @return [nil]
  describe 'estimates_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
