=begin
#Syncro

#Welcome to the official Syncro API Docs.  To use these docs, you will need an active Syncro account. You can sign up for one here: [Syncro](https://syncromsp.com)  If you already have an active account, fill in your subdomain below and then click \"Authorize\" and fill in your api-key. The key is specific to your user account so it is found on the your user profile page.  Please review the [API License Agreement](https://syncromsp.com/syncromsp-api-license-agreement/) before using our API. By accessing our API, you are agreeing to the API License Agreement.  Please note there is a rate limit of 180 requests per minute per IP address on API Usage.    

OpenAPI spec version: v1
Contact: help@syncromsp.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.25
=end

require 'spec_helper'
require 'json'

# Unit tests for WmSyncromspSwaggerClient::InvoiceLineItemApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'InvoiceLineItemApi' do
  before do
    # run before each test
    @instance = WmSyncromspSwaggerClient::InvoiceLineItemApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InvoiceLineItemApi' do
    it 'should create an instance of InvoiceLineItemApi' do
      expect(@instance).to be_instance_of(WmSyncromspSwaggerClient::InvoiceLineItemApi)
    end
  end

  # unit tests for invoices_id_line_items_line_item_id_delete
  # Deletes an a line item of an invoice by ID
  # This deletes an existing Invoice&#x27;s line item
  # @param id ID of Invoice to delete
  # @param line_item_id ID of line item to update
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'invoices_id_line_items_line_item_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for invoices_id_line_items_line_item_id_put
  # Updates an a line item of an invoice by ID
  # This updates an existing Invoice&#x27;s line item, all parameters overwrite existing params
  # @param id ID of Invoice to update
  # @param line_item_id ID of line item to update
  # @param [Hash] opts the optional parameters
  # @option opts [Object] :body ID of line item to update
  # @return [nil]
  describe 'invoices_id_line_items_line_item_id_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for invoices_id_line_items_post
  # Creates a new line item
  # Required permission: Invoices - Edit 
  # @param id ID of Invoice to update
  # @param [Hash] opts the optional parameters
  # @option opts [Object] :body ID of line item to update
  # @return [nil]
  describe 'invoices_id_line_items_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
