=begin
#Syncro

#Welcome to the official Syncro API Docs.  To use these docs, you will need an active Syncro account. You can sign up for one here: [Syncro](https://syncromsp.com)  If you already have an active account, fill in your subdomain below and then click \"Authorize\" and fill in your api-key. The key is specific to your user account so it is found on the your user profile page.  Please review the [API License Agreement](https://syncromsp.com/syncromsp-api-license-agreement/) before using our API. By accessing our API, you are agreeing to the API License Agreement.  Please note there is a rate limit of 180 requests per minute per IP address on API Usage.    

OpenAPI spec version: v1
Contact: help@syncromsp.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.25
=end

require 'spec_helper'
require 'json'

# Unit tests for WmSyncromspSwaggerClient::InvoiceApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'InvoiceApi' do
  before do
    # run before each test
    @instance = WmSyncromspSwaggerClient::InvoiceApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InvoiceApi' do
    it 'should create an instance of InvoiceApi' do
      expect(@instance).to be_instance_of(WmSyncromspSwaggerClient::InvoiceApi)
    end
  end

  # unit tests for invoices_get
  # Returns a paginated list of Invoices
  # Required permission: Invoices - List/Search 
  # @param [Hash] opts the optional parameters
  # @option opts [BOOLEAN] :paid Whether or not the returned list of invoices has been marked as paid
  # @option opts [BOOLEAN] :unpaid Whether or not the returned list of invoices has been marked as unpaid
  # @option opts [Integer] :ticket_id Any invoices attached to a Ticket ID
  # @option opts [String] :since_updated_at Any invoices updated since a date
  # @option opts [Integer] :page Returns provided page of results, each &#x27;page&#x27; contains 25 results
  # @return [nil]
  describe 'invoices_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for invoices_id_delete
  # Deletes an invoice by ID
  # Returns 200 even if the delete fails
  # @param id ID of Invoice to delete
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'invoices_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for invoices_id_email_post
  # Sends invoice to customer
  # Required permission: Invoices - View Details 
  # @param id ID of Invoice which will be emailed
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'invoices_id_email_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for invoices_id_get
  # Retrieves an Invoice by ID or Number
  # Required permission: Invoices - View Details 
  # @param id ID or Number of Invoice to retrieve
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2002]
  describe 'invoices_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for invoices_id_print_post
  # Queues a print job for an invoice
  # Required permission: Invoices - View Details 
  # @param id The ID of the Invoice to print
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'invoices_id_print_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for invoices_id_put
  # Updates an existing invoice by ID
  # This updates an existing Invoice, all parameters overwrite existing params
  # @param id ID of Invoice to update
  # @param [Hash] opts the optional parameters
  # @option opts [Body13] :body Invoice properties to update
  # @return [nil]
  describe 'invoices_id_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for invoices_id_ticket_get
  # Returns the associated ticket for an invoice
  # Required permissions: \&quot;Invoices - View Details\&quot; and \&quot;Tickets - View Details\&quot; 
  # @param id ID of Invoice whose Ticket will be returned
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'invoices_id_ticket_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for invoices_post
  # Creates an Invoice
  # Required permission: Invoices - Create 
  # @param [Hash] opts the optional parameters
  # @option opts [Body12] :body Invoice object that needs to be added
  # @return [nil]
  describe 'invoices_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
