=begin
#Syncro

#Welcome to the official Syncro API Docs.  To use these docs, you will need an active Syncro account. You can sign up for one here: [Syncro](https://syncromsp.com)  If you already have an active account, fill in your subdomain below and then click \"Authorize\" and fill in your api-key. The key is specific to your user account so it is found on the your user profile page.  Please review the [API License Agreement](https://syncromsp.com/syncromsp-api-license-agreement/) before using our API. By accessing our API, you are agreeing to the API License Agreement.  Please note there is a rate limit of 180 requests per minute per IP address on API Usage.    

OpenAPI spec version: v1
Contact: help@syncromsp.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.25
=end

require 'spec_helper'
require 'json'

# Unit tests for WmSyncromspSwaggerClient::LineItemApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'LineItemApi' do
  before do
    # run before each test
    @instance = WmSyncromspSwaggerClient::LineItemApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LineItemApi' do
    it 'should create an instance of LineItemApi' do
      expect(@instance).to be_instance_of(WmSyncromspSwaggerClient::LineItemApi)
    end
  end

  # unit tests for line_items_get
  # Returns a paginated list of Line Items
  # Required permission: Global Admin 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :invoice_id Returns Line Items that belong to an Invoice ID
  # @option opts [Integer] :estimate_id Returns Line Items that belong to an Estimate ID
  # @option opts [BOOLEAN] :invoice_id_not_null Returns Line Items that belong to any Invoice
  # @option opts [BOOLEAN] :estimate_id_not_null Returns Line Items that belong to any Estimate
  # @return [nil]
  describe 'line_items_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
