=begin
#Syncro

#Welcome to the official Syncro API Docs.  To use these docs, you will need an active Syncro account. You can sign up for one here: [Syncro](https://syncromsp.com)  If you already have an active account, fill in your subdomain below and then click \"Authorize\" and fill in your api-key. The key is specific to your user account so it is found on the your user profile page.  Please review the [API License Agreement](https://syncromsp.com/syncromsp-api-license-agreement/) before using our API. By accessing our API, you are agreeing to the API License Agreement.  Please note there is a rate limit of 180 requests per minute per IP address on API Usage.    

OpenAPI spec version: v1
Contact: help@syncromsp.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.25
=end

require 'spec_helper'
require 'json'

# Unit tests for WmSyncromspSwaggerClient::ProductSerialApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ProductSerialApi' do
  before do
    # run before each test
    @instance = WmSyncromspSwaggerClient::ProductSerialApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ProductSerialApi' do
    it 'should create an instance of ProductSerialApi' do
      expect(@instance).to be_instance_of(WmSyncromspSwaggerClient::ProductSerialApi)
    end
  end

  # unit tests for products_product_id_product_serials_attach_to_line_item_post
  # Adds Product Serials to a Line Item
  # Required permission: Products - List/Search Additional permissions required depending on \&quot;record_type\&quot;: - LineItem: \&quot;Invoices - Edit\&quot; or \&quot;Estimates - Edit\&quot; - TicketLineItem: Tickets - Edit 
  # @param product_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Body23] :body 
  # @return [nil]
  describe 'products_product_id_product_serials_attach_to_line_item_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for products_product_id_product_serials_get
  # Returns a paginated list of Product_serials
  # Required permission: Products - List/Search 
  # @param product_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :status Possible values are reserved, sold, returned, in_transfer, breakage, used_in_refurb, in_stock
  # @option opts [Integer] :page Returns provided page of results, each &#x27;page&#x27; contains 100 result
  # @return [InlineResponse2003]
  describe 'products_product_id_product_serials_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for products_product_id_product_serials_id_put
  # Updates an existing Product Serial by ID
  # Required permission: Products - Edit 
  # @param product_id 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [Body22] :body Product Serial object that needs to be updated
  # @return [nil]
  describe 'products_product_id_product_serials_id_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for products_product_id_product_serials_post
  # Creates a Product Serial
  # Required permission: Products - Edit 
  # @param product_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Body21] :body Product Serial object that needs to be added
  # @return [nil]
  describe 'products_product_id_product_serials_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
