=begin
#Syncro

#Welcome to the official Syncro API Docs.  To use these docs, you will need an active Syncro account. You can sign up for one here: [Syncro](https://syncromsp.com)  If you already have an active account, fill in your subdomain below and then click \"Authorize\" and fill in your api-key. The key is specific to your user account so it is found on the your user profile page.  Please review the [API License Agreement](https://syncromsp.com/syncromsp-api-license-agreement/) before using our API. By accessing our API, you are agreeing to the API License Agreement.  Please note there is a rate limit of 180 requests per minute per IP address on API Usage.    

OpenAPI spec version: v1
Contact: help@syncromsp.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.25
=end

require 'spec_helper'
require 'json'

# Unit tests for WmSyncromspSwaggerClient::TicketTimerApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'TicketTimerApi' do
  before do
    # run before each test
    @instance = WmSyncromspSwaggerClient::TicketTimerApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TicketTimerApi' do
    it 'should create an instance of TicketTimerApi' do
      expect(@instance).to be_instance_of(WmSyncromspSwaggerClient::TicketTimerApi)
    end
  end

  # unit tests for ticket_timers_get
  # Returns a paginated list of Ticket Timers
  # Required permission: Ticket Timers - Overview 
  # @param [Hash] opts the optional parameters
  # @option opts [DateTime] :created_at_lt Returns Ticket Timers created before the date. Example \&quot;2019-01-22\&quot;
  # @option opts [DateTime] :created_at_gt Returns Ticket Timers created after the date. Example \&quot;2019-12-22\&quot;
  # @option opts [Integer] :page Returns provided page of results, each &#x27;page&#x27; contains 25 results
  # @return [nil]
  describe 'ticket_timers_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
