=begin
#Syncro

#Welcome to the official Syncro API Docs.  To use these docs, you will need an active Syncro account. You can sign up for one here: [Syncro](https://syncromsp.com)  If you already have an active account, fill in your subdomain below and then click \"Authorize\" and fill in your api-key. The key is specific to your user account so it is found on the your user profile page.  Please review the [API License Agreement](https://syncromsp.com/syncromsp-api-license-agreement/) before using our API. By accessing our API, you are agreeing to the API License Agreement.  Please note there is a rate limit of 180 requests per minute per IP address on API Usage.    

OpenAPI spec version: v1
Contact: help@syncromsp.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.25
=end

require 'spec_helper'
require 'json'

# Unit tests for WmSyncromspSwaggerClient::TimelogApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'TimelogApi' do
  before do
    # run before each test
    @instance = WmSyncromspSwaggerClient::TimelogApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TimelogApi' do
    it 'should create an instance of TimelogApi' do
      expect(@instance).to be_instance_of(WmSyncromspSwaggerClient::TimelogApi)
    end
  end

  # unit tests for timelogs_get
  # Returns a paginated list of Timelogs
  # Users with permission \&quot;Timelogs - Manage\&quot; may see timelogs for any/all users. Otherwise, results scoped to current user. 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :user_id Returns Timelogs that belong to a User
  # @return [nil]
  describe 'timelogs_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for timelogs_last_get
  # Returns last Timelog
  # Users with permission \&quot;Timelogs - Manage\&quot; may see timelogs for any/all users. Otherwise, results scoped to current user. 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :user_id Returns Timelogs that belong to a User. The default is current user ID.
  # @return [nil]
  describe 'timelogs_last_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for timelogs_put
  # Updates a Timelog
  # Users with permission \&quot;Timelogs - Manage\&quot; may see timelogs for any/all users. Otherwise, results scoped to current user. 
  # @param [Hash] opts the optional parameters
  # @option opts [Body38] :body 
  # @return [nil]
  describe 'timelogs_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
