=begin
#Syncro

#Welcome to the official Syncro API Docs.  To use these docs, you will need an active Syncro account. You can sign up for one here: [Syncro](https://syncromsp.com)  If you already have an active account, fill in your subdomain below and then click \"Authorize\" and fill in your api-key. The key is specific to your user account so it is found on the your user profile page.  Please review the [API License Agreement](https://syncromsp.com/syncromsp-api-license-agreement/) before using our API. By accessing our API, you are agreeing to the API License Agreement.  Please note there is a rate limit of 180 requests per minute per IP address on API Usage.    

OpenAPI spec version: v1
Contact: help@syncromsp.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.25
=end

require 'spec_helper'
require 'json'

# Unit tests for WmSyncromspSwaggerClient::VendorApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'VendorApi' do
  before do
    # run before each test
    @instance = WmSyncromspSwaggerClient::VendorApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of VendorApi' do
    it 'should create an instance of VendorApi' do
      expect(@instance).to be_instance_of(WmSyncromspSwaggerClient::VendorApi)
    end
  end

  # unit tests for vendors_get
  # Returns a paginated list of Vendors
  # Required permission: Vendors - List 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Returns provided page of results, each &#x27;page&#x27; contains 100 result
  # @return [nil]
  describe 'vendors_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for vendors_id_get
  # Retrieves a Vendor Page
  # Required permission: Vendors - View Details 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2004]
  describe 'vendors_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for vendors_id_put
  # Updates an existing Vendor page by ID
  # Required permission: Vendors - Edit 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [Object] :body 
  # @return [nil]
  describe 'vendors_id_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for vendors_post
  # Creates a Vendor
  # Required permission: Vendors - New 
  # @param [Hash] opts the optional parameters
  # @option opts [Object] :body 
  # @return [nil]
  describe 'vendors_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
