=begin
#Syncro

#Welcome to the official Syncro API Docs.  To use these docs, you will need an active Syncro account. You can sign up for one here: [Syncro](https://syncromsp.com)  If you already have an active account, fill in your subdomain below and then click \"Authorize\" and fill in your api-key. The key is specific to your user account so it is found on the your user profile page.  Please review the [API License Agreement](https://syncromsp.com/syncromsp-api-license-agreement/) before using our API. By accessing our API, you are agreeing to the API License Agreement.  Please note there is a rate limit of 180 requests per minute per IP address on API Usage.    

OpenAPI spec version: v1
Contact: help@syncromsp.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.25
=end

require 'spec_helper'
require 'json'

# Unit tests for WmSyncromspSwaggerClient::WikiPageApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'WikiPageApi' do
  before do
    # run before each test
    @instance = WmSyncromspSwaggerClient::WikiPageApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WikiPageApi' do
    it 'should create an instance of WikiPageApi' do
      expect(@instance).to be_instance_of(WmSyncromspSwaggerClient::WikiPageApi)
    end
  end

  # unit tests for wiki_pages_get
  # Returns a paginated list of Wiki Pages
  # Required permission: Documentation - Allow Usage 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Returns provided page of results, each &#x27;page&#x27; contains 100 result
  # @return [nil]
  describe 'wiki_pages_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for wiki_pages_id_delete
  # Deletes a Wiki Page by ID
  # Required permission: Documentation - Delete 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'wiki_pages_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for wiki_pages_id_get
  # Retrieves a Wiki Page
  # Required permission: Documentation - Allow Usage 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2005]
  describe 'wiki_pages_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for wiki_pages_id_put
  # Updates an existing Wiki Page by ID
  # Required permission: Documentation - Edit 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [Body43] :body Wiki Page object that needs to be updated
  # @return [nil]
  describe 'wiki_pages_id_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for wiki_pages_post
  # Creates a Wiki Page
  # Required permission: Documentation - Create 
  # @param [Hash] opts the optional parameters
  # @option opts [Body42] :body Wiki Page object that needs to be added
  # @return [nil]
  describe 'wiki_pages_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
